version: '3'

services:
  wiki:
    image: requarks/wiki:latest
    container_name: wiki-public
    restart: unless-stopped
    ports:
      - "3003:3000"
    environment:
      - DB_TYPE=sqlite
      - DB_FILE=/data/wiki.db
    volumes:
      - wiki-public-data:/data

volumes:
  wiki-public-data:

